### PR TITLE
Test the maven compilation using github actions

### PR DESCRIPTION
**Pull request by andrewbaxter439**
As a potential way of testing whether updated pushes to the main/development branch can still compile? May be far, far, far too annoying if it's doing all the development ones, but perhaps worth a test for now?

### CODE REVIEW

**Comment by andrewbaxter439** [comment]
Well it's _sort of_ working just now, as in it's detecting the compilation errors in the `develop` branch:

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project model: Compilation failure
Error:  /home/runner/work/SimPaths/SimPaths/src/main/java/simpaths/data/Parameters.java:[2519,21] cannot find symbol
Error:    symbol:   method replaceValue(int,java.lang.Object)
Error:    location: variable valueMap of type microsim.data.MultiKeyCoefficientMap
```
Added in https://github.com/centreformicrosimulation/SimPaths/commit/8595513aa6426b19f93c3f40860f04c1438ef172

If build-checking is a useful feature, I'll wait till there's a stable development version before running again. Perhaps only useful on pull requests to `main`!

**Comment by andrewbaxter439** [comment]
(apologies @pbronka that commit fdc01df above seems to have been included in this new branch?)

**Comment by pbronka** [comment]
1. I think the way to fix the compilation error is to update JAS-mine-core to 4.3.4 in the pom.xml file (which I did now on the develop branch)
2. No worries. I accidently uploaded a file that shouldn't have been uploaded and that commit is a part of cleaning that up.

**Comment by andrewbaxter439** [comment]
1. Ah I see! Do close issue #19 then if it's a new method in JAS-mine-core.

**Comment by pbronka** [comment]
Thanks for this @andrewbaxter439 Would you mind providing some instructions regarding usage?

**Comment by andrewbaxter439** [comment]
Thanks @pbronka - that's it working now. Have it set up to detect pull requests:

```
on:
  pull_request:
    branches: [ "main", "develop" ]
```
and run a test to see if the whole thing compiles without error:
```

```
    - name: Build with Maven
      run: mvn -B package --file pom.xml
```

This should only trigger when someone else wants to do a new pull to one of those branches. It should automatically run the test, show the results in the pull request as well as in Actions (e.g. https://github.com/andrewbaxter439/SimPaths/actions). Should then provide a new marker of whether things can still compile, but can be ignored if there's a need to pull anyway. Can be turned off by deleting `.github/workflows/maven.yml`.

**Comment by pbronka** [comment]
Thanks, that's a very nice feature!

**Pull request merged**
